### ISSUE TITLE
Prima HTML!

### ISSUE THREAD

**Issue by KrijnHoetmer** [gitazeinstra/the-client-website#1]
Weinig op aan te merken voor nu, maar kom snel langs voor meer feedback :) Enige dingetje; is je pagina in het Engels of het Nederlands?

https://github.com/gitazeinstra/the-client-website/blob/264ddfb4aa098323e432823bd8f94a9d74d3ea74/index.html#L2

**Comment by gitazeinstra** [comment]
Pagina is Nederlands. Dankjewel voor het melden, is aangepast naar nl!
