### ISSUE TITLE
Non focusable menu trigger

### ISSUE THREAD

**Issue by MartijnNieuwenhuizen** [gitazeinstra/the-client-website#3]
Your menu trigger is created with this piece of code
```html
<div class="mobile-navbar-icon">
    <span class="bar"></span>
    <span class="bar"></span>
    <span class="bar"></span>
</div>
```
But a div/span element isn't focusable. Could you improve this bit of HTML?

**Comment by gitazeinstra** [comment]
I have changed it to a `<button>`. Thank you!
