### ISSUE TITLE
Quotes

### ISSUE THREAD

**Issue by MartijnNieuwenhuizen** [gitazeinstra/the-client-website#4]
https://github.com/gitazeinstra/the-client-website/blob/b2ec2e16f0540960921bd6fb1dd5ccf6a9f826f7/index.html#L169

You have a view quotes in your HTML. Although the HTML looks good, there are elements that are more suitable for this type of content (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote)

**Comment by gitazeinstra** [comment]
I have changed it, thank you!
