### ISSUE TITLE
Optional!

### ISSUE THREAD

**Issue by MartijnNieuwenhuizen** [gitazeinstra/the-client-website#6]
https://github.com/gitazeinstra/the-client-website/blob/b2ec2e16f0540960921bd6fb1dd5ccf6a9f826f7/js/main.js#L6

This block of code is executed for every pixel that the user scrolls. In this code, you do a lookup in the DOM (`querySelector`). This isn't needed for every pixel that you scroll, but just once :)

**Comment by gitazeinstra** [comment]
Const navbar & const scrollBtn are now outside the function. Thank you!
